### ISSUE TITLE
p2p-client functional changes

### ISSUE THREAD

**Issue by HeyHoProBro** [justarrived/just_match_api#1024]
Initial functional changes that would be useful for the p2p-client.

Users
- [x]  Users (advertisers) can create jobs (high prio) (PR https://github.com/justarrived/just_match_api/pull/1029, deployed to sandbox)
- [x] Users can be either job applicants or job advertisers (low prio if all Users can create jobs)
- [ ] Users can add alternative contact person or phone number (low prio)
- [ ] Users can add array with favorite locations (low prio)

Ratings
- [ ] Ratings with 3 different 1-5 values. punctuality, communication, quality. (medium prio)

**Comment by buren** [comment]
"Regular" users are now allowed to create jobs on `sandbox-api.justarrived.xyz`. Happy hacking!

**Comment by buren** [comment]
💤
