### ISSUE TITLE
Inconsistency in entries with translated_text

### ISSUE THREAD

**Issue by bex1** [justarrived/just_match_api#1025]
To make entries with translated_text objects consistent:

Missing language relation:

- [x] application/job user (ad97e96)
- [x] country (#1049)
- [x] faq (#1049)
- [x] user-gender (#1049)
- [x] user-image-category (#1049)
- [x] user-status (#1049)
- [x] language  (#1049)

Missing language_id in attributes:

- [x] user_gender (#1049)

**Comment by buren** [comment]
Seems like `language` is already included for `/countries`
<img width="319" alt="screen shot 2017-04-02 at 15 09 16" src="https://cloud.githubusercontent.com/assets/922411/24587421/6a349ad8-17b6-11e7-8b7b-fc8894584b59.png">

**Comment by bex1** [comment]
🥇
