### ISSUE TITLE
Users creating double accounts

### ISSUE THREAD

**Issue by annahornmark** [justarrived/just_match_api#1063]
### Users creating double accounts

Happens more and more.
This is a big problem for us, especially since we do not know with which email to reach the person, and their phone number is most likely registered on the first user, and can not be registered on the one they're actually using and making applications with

What to do?
How to make them reach out to us for help to find their "old" acccount, instead of creating a new one?

**Comment by lovawestlund** [comment]
I wonder how long this is going to be a problem. Because the problem exists because of the transfer from Wintrgarden. Or am I wrong? @annahornmark

**Comment by annahornmark** [comment]
Good point @lovawestlund 
However, it was an import of 800 ~ish users, so there might me many more to come...

**Comment by buren** [comment]
Bex and I are working on some stuff to mitigate this:

If a user has tried to create an account that already exists we'll clearly prompt them to go through a password reset. We'll also see if we can be smarter about checking email/phone/ssn even after a duplicated registration, and then prompt them to contact us to merge the account.

**Comment by buren** [comment]
We've added a couple of feature in the web app that aims to mitigate / lessen the extent this happens.
