### ISSUE TITLE
ERROR when activating invoice from admin

### ISSUE THREAD

**Issue by annahornmark** [justarrived/just_match_api#1081]
![image](https://cloud.githubusercontent.com/assets/21364952/25121582/6e2d78ee-2422-11e7-9860-bc9269850c54.png)

![image](https://cloud.githubusercontent.com/assets/21364952/25121593/78e752b4-2422-11e7-957b-74356fa1ef9b.png)

Could it be since the change you did last week, when I requested a "confirmation pop up"?
Haven't activated an invoice since then

**Comment by buren** [comment]
Rookie mistake! I accidentally forgot to 🔪  a line used for debugging 😝 

Fix :shipit:
