### ISSUE TITLE
Ban user as admin

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#110]
Allow admin users to ban any user.

**Comment by buren** [comment]
What does ban mean? Do we stop the banned user from logging in? @FivelFred

**Comment by FivelFred** [comment]
Yes. The idea is to restrict them from logging in. They should get an error message that they have gotten their accounts disabled due to inapporiate usage and if they wish to use it again they should contact help@justarrived.se

**Comment by FivelFred** [comment]
Would be neat to be able to ban on email AND personal number / samordnings number.
