### ISSUE TITLE
Be able to search on user_id in user listing

### ISSUE THREAD

**Issue by annahornmark** [justarrived/just_match_api#1146]
Names are growing more and more common in our system. We have therefore started to use `user_id` in a lot of lists, communication etc. Would be great if we also could search on an id in user listing view.

**Comment by buren** [comment]
@annahornmark you can always add that to the URL yourself :) `https://admin.justarrived.se/users/%{user_id}`. Could ofc add it as a filter too, if you want? 🙃

**Comment by annahornmark** [comment]
Yes please. 
More for the reason that I soon have a team of five to communicate with regarding how we use the system, and it would be awesome if all the filtering is done the same way, regardless of what you need to filter by
