### ISSUE TITLE
Implement fixed prices for jobs

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#124]
The job price should be fixed.. 

- [x] ~~what should the hourly rate be?~~
- [x] ~~should it be configurable by the admin on the fly or hardcoded?~~

- [ ] Implement: 70 (minimum), 80 (recommended) eller 100 (generous) SEK

**Comment by buren** [comment]
Has this been decided? @justarrived/product

**Comment by buren** [comment]
Ping @FivelFred

**Comment by FivelFred** [comment]
70 (minimum), 80 (recommended) eller 100 (generous) SEK should be the choices. For the corporation purchasing the amount will double due to taxes and social fees. Everything ex VAT which is added on the bill

**Comment by FivelFred** [comment]
But the total ( hourly salary ×2) should be displayed prior to accepting the job add

**Comment by buren** [comment]
@FivelFred does our payment provider support jobs created by companies and individuals?

**Comment by FivelFred** [comment]
It supports both but we want to limit it to companies in the first release due to a number of reason

**Comment by buren** [comment]
:ok: :cool:

**Comment by buren** [comment]
ping @FivelFred

**Comment by FivelFred** [comment]
The salarylevels might come to change. But I will keep you posted. We are in discussions with various unions.

**Comment by FivelFred** [comment]
This is done. 105, 115, 125 gross salary is the set levels now.
