### ISSUE TITLE
Allow users to turn off notification emails

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#180]
Some emails still need to be sent, for example Forgot password emails

**Comment by buren** [comment]
@FivelFred any particular thoughts on how users should be able to control what notifications they're sent?

**Comment by FivelFred** [comment]
You are right. As that need or desire to unsubscribe would arise when a email is recieved I suggest we make connect that feature to the email send outs. Like an unsubscribe link in the bottom maybe we could have a link that redirects you to a view where you can turn on and off notification for the various send outs?

**Comment by FivelFred** [comment]
Nice and simple example from InVision. In their email they have  a hyperlink which says "Edit your email preferences". That takes you to this checkbox view of different notifications. 
![skarmavbild 2016-03-14 kl 14 27 18]
![invision example](https://cloud.githubusercontent.com/assets/16607246/13746117/0ae8814a-e9f2-11e5-9d55-d26f490ca597.png)
(https://cloud.githubusercontent.com/assets/16607246/13746075/d4d9ae94-e9f1-11e5-961d-b42e74f9f9f2.png)
