### ISSUE TITLE
Setup google API key to avoid query limits

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#185]
See https://github.com/alexreisner/geocoder#google-google

**Comment by buren** [comment]
Actually https://github.com/alexreisner/geocoder#google-google might be more appropriate. See googles documentation https://developers.google.com/maps/pricing-and-plans/

**Comment by buren** [comment]
@FivelFred could you perhaps create a Google Maps API key (you create it in something thats called Google Developer Console) so that we can make authenticated request to them, otherwise will risk that the our geocoding will stop working if we get a sudden traffic spike :) If you have any questions how to create it just ask :)

**Comment by buren** [comment]
ping @FivelFred

**Comment by FivelFred** [comment]
I'm on it! Remind me by the end of the week if not fixed

**Comment by FivelFred** [comment]
Done! Sent.

**Comment by buren** [comment]
Closed by #247
