### ISSUE TITLE
Add Category & JobCategory models

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#190]
- [ ] Define what how the categories should work and how the differ from `Skill`s
- [ ] Implement
- [ ] Profit :)

**Comment by buren** [comment]
Related to #2

**Comment by buren** [comment]
As I remember it 

1. The job creator chooses a category 
2. We validate that they category is allowed 
3. Save the job along with the category 
4. When an applicant has been chosen and confirmed we send the category (along with other data) to our payment provider

@FivelFred :point_up: correct?

**Comment by FivelFred** [comment]
Correct.

The only thing I would like to add to that is how we communicate what categories are allowed and which ones are not. 

My suggestion is that we provide the entire list and that the user can use an autofill function to choose a job. If the user selects a job that is not allowed we need to inform them with a disclaimer. 

Is that doable @mickeek ? @buren ?

**Comment by buren** [comment]
@FivelFred definitely doable. I would however suggest that we don't allow anyone to create a job with a non-allowed category, that way we eliminate a bunch of edge cases and I don't think it will be very common..

**Comment by FivelFred** [comment]
True. The best thing would be if it isn´t possible to succeed if a non-eligible category is chosen. That way they will still get the info why etc.
