### ISSUE TITLE
Languages seed

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#191]
* Add all / most languages in the world
* Add a flag that indicates whether the languages is officially supported by the system, in other words is translated

**Comment by buren** [comment]
Related to #2

**Comment by buren** [comment]
@FivelFred there are a ton of languages out there.. we need to find a suitable subset that the users can chose from. (Meaning the languages they speak..)

**Comment by FivelFred** [comment]
Swedish, English, Farsi, Dari, Tigrinja and "Modern Standard Arabic"

**Comment by FivelFred** [comment]
thoose are the only languages supported by the system for the first release

**Comment by buren** [comment]
@FivelFred cool.

Its been discussed that we should allow users to add all languages they know even though its not supported by the platform. I.e a user that speaks french would probably want to add that, so it would be nice to provide a list of maybe ~100-200 of the most common languages. I'm not sure were we'd get that list, but its probably not that hard to find..

**Comment by FivelFred** [comment]
Ah ok. Got it!

I think we could use the index wikipedia set up. It has both the english name and native name of the language which is beneficial. We will need to add some but it is a good start.

https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code

**Comment by buren** [comment]
Haha, I love the fact that the wikimedia list :point_up: includes klingon :)
