### ISSUE TITLE
On job attribute update notify job users 

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#204]
Users want to know when a job has been updated, so send all `Job#users` a notification email.

__Questions__

@FivelFred:

* On what attribute updates should we notify the user?
  - `Job#job_date` seems like a given

**Comment by buren** [comment]
ping @FivelFred

**Comment by buren** [comment]
It shouldn't be allowed in the first version and for future versions a new issue will be created..

**Comment by FivelFred** [comment]
Nice to have would be a notification that the job has been updated and a request to accept the new terms, like the "you have 12h to accept that you are granted notification"
