### ISSUE TITLE
Ability to view jobs for user

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#213]
## Roles

__Self User (the user that is logged in)__

* All jobs they are "connected" to
  - _Filter_: On current "state" (currently applied to, hired, previous)
  - _Filter_: accepted applicant
  - _Filter_: job owner

__Any user__

* .. ?

@justarrived/product what can logged in users see about other users? Can they view others passed jobs?

__Job owner where user is an applicant__

* All jobs where the user has been the accepted user

## Routing

There are a couple of ways we could route this..

* Either we could go with a single route which could look something like this:

```
users/1/jobs
users/1/jobs?filter[accepted_applicant]=true
users/1/jobs?filter[accepted_applicant]=false
users/1/jobs?filter[owner]=true
```

the above follows the [JSON API filter format](http://jsonapi.org/format/#fetching-filtering). The standard has now opinions about routs, but says if you do it using params this is how it should look.

* Go with multiple routes

```
users/1/jobs
users/1/owned_jobs
users/1/accepted_applicant_jobs
```

@justarrived/frontend any thoughts on the routing above :point_up:?

**Comment by buren** [comment]
@nigr any thoughts on :point_up:?

**Comment by buren** [comment]
@FivelFred what can logged in users see about other users? Can they view others passed jobs? (see :point_up:)

**Comment by FivelFred** [comment]
I can't see why an applicant should see any information about another applicant.

**Comment by FivelFred** [comment]
I however think that a company should be able to view all availible information of a user that has applied for a job. Previous jobs and profile.

**Comment by FivelFred** [comment]
I think we can set this as nice to have @buren. It is a nice feature but not crucial to make the application functionable.
