### ISSUE TITLE
Proper support for company accounts 

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#230]
@FivelFred we need to discuss what the differences are between personal and company accounts. 

The goal in this issue would be to create a list of updates that we need to implement to properly support this :) anything in particular you see?

**Comment by buren** [comment]
ping @FivelFred

**Comment by FivelFred** [comment]
Nice to have in the long term would be to provide customized starting pages for each kind of user

**Comment by buren** [comment]
Also the payment integration could require us to send different data depending on the user type.

**Comment by FivelFred** [comment]
- Q&A could differ between the two (nice to have - prio 4)
- The hambuger meny should have "söka jobb" for applicant and "lägg upp jobb" for company (should have - prio 3)
