### ISSUE TITLE
Don't allow updates to Job when job has been approved and accepted

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#234]
We don't want the `Job#owner` to update the details after the job has been approved and accepted by the applicant (could cause gnarly disputes..).

#233 needs to be closed/fixed before this feature is possible..

@FivelFred what are the rules around this?

**Comment by buren** [comment]
ping @FivelFred

**Comment by FivelFred** [comment]
See #204 @buren

**Comment by buren** [comment]
One future nice to have as noted in #204, is

https://github.com/justarrived/just_match_api/issues/204#issuecomment-193381483
> Nice to have would be a notification that the job has been updated and a request to accept the new terms, like the "you have 12h to accept that you are granted notification"

**Comment by FivelFred** [comment]
No more input needed on this?

**Comment by buren** [comment]
Nope, for the time being I'll just not allow it at all :)
