### ISSUE TITLE
Remove user as accepted if they haven't confirmed they can perform a job after 18 hours

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#242]
__Unless `JobUser#will_perform` is set to true__

- [ ] Add a scheduled check that sets `JobUser#accepted` to false after 18 hours from setting it to true
  - Depends on #144
- [ ] `JobUser` confirmation overdue query 
- [ ] Send an email to the `Job#owner`
- [ ] The `Job#owner` should be allowed to accept the same user again

**Comment by buren** [comment]
Seems like 24h could be reasonable. If its only 12h the job owner could accept someone at 9pm and then the time would be up at 9am which seems a little unfair :)

**Comment by FivelFred** [comment]
Shall we make it 18 hours? :)

**Comment by FivelFred** [comment]
One of our USP is that the application is easy to use and FAST so 24 hours feels to slow. Maybe it should be 4 hours? Or not hehe

**Comment by buren** [comment]
18h seems reasonable

**Comment by buren** [comment]
Closed in favour of PR #256.
