### ISSUE TITLE
View rules for ratings

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#259]
The current implementation does not allow any users (except admins) to view any rating information about each other at all (not even aggregates).

In our current mock ups there are aggregates displayed in most user listing views.. 

I have a few concerns ;) 

* most users will have very few ratings (none to a few), meaning that each rating will be very, very important
* it might increase the barrier to entry for an unrated/first time user
* if a users first rating is bad it might be very hard to be re-hired
* a few "elite" users with high ratings would get hired for almost everything they apply for, leaving the majority with little left (basically exactly the same problem as app store and Android play have.) 

@FivelFred any thoughts?

**Comment by FivelFred** [comment]
jag funderar på om vi ska vänta med att redovisa betyget de första månaderna. vi skulle kunna köra utan tillsvidare för att få in användare och för att få upp antalet betyg innan vi släpper funktionen.

ett annat bra förslag från caroline he var att man skulle kunna tillåta folk att rekommendera varandra in i tjänsten. när man blir rekommenderad får man dels ett betyg direkt och det driver antalet användare genom att man kan bjuda in.

**Comment by buren** [comment]
As discussed in slack 

> we could just wait and not show anything for now and just collect the ratings, later we could analyse how it would look with real data
