### ISSUE TITLE
Setup production environment

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#406]
- [x] Sweepers and other background tasks
- [x] Admin accounts
- [x] Verify Frilans Finans seed data

....

@FivelFred anything else you can come up with?

**Comment by FivelFred** [comment]
No, not top of mind 


Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Jacob Burenstam <notifications@github.com> 
Datum: 05-20-2016  17:14  (GMT+01:00) 
Till: justarrived/just_match_api <just_match_api@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: [justarrived/just_match_api] Setup production environment (#406) 



 Sweepers and other background tasks

 Admin accounts

 Verify Frilans Finans seed data


....

@FivelFred anything else you can come up with?
