### ISSUE TITLE
Add sms support for important notifications

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#423]
Add notifications for:

-...

**Comment by buren** [comment]
@FivelFred what notifications do you feel to be most important? 

Arriver confirmation that they will perform the job seems like a given.

**Comment by FivelFred** [comment]
High priority
- When you have been accepted for a job- When the job performer has confirmed that the job is done (a sms should be sent to the job owner)
Medium priority
- When a new chat is initiated by a job owner (not for every message, only first for the job)  if a user has been inactive more than a month- When a candidate has accepted the request to perform the job
Low priority 
- A sms that there are new jobs on the platform
Will continue on the list later but these are the most important top of mind

Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: Jacob Burenstam <notifications@github.com> 
Datum: 06-10-2016  07:35  (GMT+01:00) 
Till: justarrived/just_match_api <just_match_api@noreply.github.com> 
Kopia: FivelFred <fredricghatan@gmail.com>, Mention <mention@noreply.github.com> 
Rubrik: Re: [justarrived/just_match_api] Add sms support for important
  notifications (#423) 

@FivelFred what notifications do you feel to be most important? 

Arriver confirmation that they will perform the job seems like a given.

**Comment by buren** [comment]
Related to #49
