### ISSUE TITLE
Consider adding Job#archived boolean column

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#905]

**Comment by buren** [comment]
@annahornmark would adding this make sense?

**Comment by annahornmark** [comment]
What would archiving mean in this case?
 `As in this is old news and I don't want to be bothered with it anymore` ?

**Comment by buren** [comment]
@annahornmark yeah, using it kinda like delete was actually my though :) 

Basically it would mean "Don't bother me, or users, with this in the admin/app anymore` :)

**Comment by annahornmark** [comment]
Then do it @buren
