### ISSUE TITLE
Assign responsible within operations to a job_request

### ISSUE THREAD

**Issue by annahornmark** [justarrived/just_match_api#913]
Assign responsible within operations to a job_request.
We would in the long run like this to "mean something", preferrably get a notification, sort out "my" job requests etc. 

Not sure that it per se "needs" discussion, but it would be fun!

**Comment by annahornmark** [comment]
Guessing it's the old issue with the "blank whatever" that makes it impossible to save the changes to a job request after this update?

When clicking update the API acts as if nothing happens, and the changes disappear.

**Comment by buren** [comment]
F*** I've been forgotten to add those fields to the permitted fields list...
