### ISSUE TITLE
Post job to Arbetsförmedlingen

### ISSUE THREAD

**Issue by lovawestlund** [justarrived/just_match_api#919]
I would like that all of ours job ads will automaticlly be uploaded at arbetsförmedlingen

**Comment by annahornmark** [comment]
yani **very** nice to have

**Comment by buren** [comment]
Instructions getting started:

> Direktöverföring av annonser till Platsbanken
> Om ditt företag har ett internt system där ni registrerar era platsannonser finns det möjlighet att automatiskt föra över annonserna till Platsbanken. Vi på Arbetsförmedlingen har tagit fram en XML-baserad standard för platsannonser - HR-XML-SE. Standarden baseras på det arbete som bedrivs internationellt.
> 
> Så här går det till
> 
> - Beställ information via e-post.
> - Om du saknar ett arbetsgivarkonto på vår webbplats, börja med att registrera ett konto.
> - Om du redan har konto Logga in och gör en ansökan.
> 
> - Efter godkänt avtal kan tester påbörjas.
> - XML-filerna testas i samarbete med oss. Sluttester genomförs med vår support innan vi går över i produktion.
>
> \- https://www.arbetsformedlingen.se/For-arbetsgivare/Annonsera/Direktoverforda-annonser.html

@lovawestlund could you perhaps email them and ask for access?

**Comment by lovawestlund** [comment]
Yes, I will look it up @buren

**Comment by buren** [comment]
Implemented, now we "only" need to get approved.
