### ISSUE TITLE
Implement industries 

### ISSUE THREAD

**Issue by annahornmark** [justarrived/just_match_api#935]
Tie every job to one or more industries. These should be able to use as a filter to , for example, fins every application to all cleaning jobs/ service jobs etc, and then arrange events, book interviews, send emails etc.

List of industries will come from Ops

**Comment by annahornmark** [comment]
### Further use for `industries`

Tie every `company` to an `industry`, which mostly has an use within marketing when emails etc can be targeted to segments of our customers.

**Comment by buren** [comment]
@annahornmark I guess that companies also should be connected to one, or more, industries?

**Comment by annahornmark** [comment]
I should think that more times than not, one should be enough
But sometimes, probably. @buren So more than a status flag I'm afraid...

**Comment by buren** [comment]
Ok 👍 Sometimes in dev-land means, that we need to support it :)
