### ISSUE TITLE
New queries

### ISSUE THREAD

**Issue by annahornmark** [justarrived/just_match_api#955]
### 1. How many jobs have been performed? (from, to date)
    - `Job_user` with status `will perform`and has a FF invoice connected to it with status `activated` 
### 2. How many unique users have performed jobs? (from, to date)
    - Same as the inquiry above, **but only counting every unique user_id once**!
### 3. How many "first time" users do we have within a given period?
    - Same as the inquiry above, **but excluding users  who has that status in a previous period**!

**Comment by buren** [comment]
1. https://api.justarrived.se/insights/queries/128-ongoing-jobs-between-dates?end_time=2017-03-07T22%3A59%3A59%2B00%3A00&start_time=2017-02-05T23%3A00%3A00%2B00%3A00

**Comment by annahornmark** [comment]
#2 should only list __unique__ users

**Comment by buren** [comment]
🎉 📊 📈
