### ISSUE TITLE
Sort by locale name attribute on routes

### ISSUE THREAD

**Issue by bex1** [justarrived/just_match_api#995]
Want to be able to sort on name via locale on 

- [ ] GET /api/v1/countries
- [x] GET /api/v1/languages 
- [ ] GET /api/v1/skills 
- [ ] GET /api/v1/users/statuses 
- [ ] GET /api/v1/users/genders 
- [ ] GET /api/v1/interests 

This implies that we want to be able to pass name or locale_name (if applicable) or translated_text.name as parameters to sort.

**Comment by buren** [comment]
`/users/statuses`, `/users/genders` requires that `JsonApiHelpers::Serializers::Datum` has sorting capabilities..

**Comment by bex1** [comment]
@buren This is not needed anymore. 😄 

See:
https://github.com/justarrived/just-match-web/issues/510
